<footer class="page-footer">
    <div class="footer-copyright">
        <div class="container">
            <h6 align="right">Universidad Nacional de San Agustin de Arequipa | Cuna Jardin</h6>
            <!--
            <span>Copyright © 2018-2019 <a class="grey-text text-lighten-4" href="http://www.unsa.edu.pe" target="_blank">Cuna Jardin</a> All rights reserved.</span>
            <span class="right"> Diseño y Desarrollo por <a class="grey-text text-lighten-4" href="http://www.unsa.edu.pe">Cuna Jardin</a></span>
            -->
        </div>
    </div>
</footer>
